name: flutter_panorama
description: "Flutter package for snaping panorama photos with OpenCV and a simple interface."
version: 1.1.0
homepage: https://github.com/RolandDumit/flutter_panorama

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  camerawesome: ^2.5.0
  sensors_plus: ^6.1.1
  opencv_dart: ^1.4.3
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0